googleapis/java-bigtable

.gitignore

Copied `.gitignore` content from the source(google-cloud-java) repository.

chore: Adding .gitignore to skip generated meta files & folders

---

google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsMergingAcceptanceTest.java
pom.xml

When the repo was first migrated from google-cloud-java the test dependency
google-cloud-conformance-tests had not yet been migrated out and released.
Now that it has, this change adds the dependency and adds back the
ReadRowsMergingAcceptanceTest which was excluded to allow compilation to
succeed.
Test imported from https://github.com/googleapis/google-cloud-java/blob/6de998cde1ab542d95af740e310ae58cb7c317a0/google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsMergingAcceptanceTest.java
Fixes #6

chore: add back ReadRowsMergingAcceptanceTest

---

google-cloud-bigtable-emulator/README.md
google-cloud-bigtable-emulator/pom.xml
google-cloud-bigtable-emulator/src/main/java/com/google/cloud/bigtable/emulator/v2/BigtableEmulatorRule.java
google-cloud-bigtable-emulator/src/main/java/com/google/cloud/bigtable/emulator/v2/Emulator.java
google-cloud-bigtable-emulator/src/test/java/com/google/cloud/bigtable/emulator/v2/BigtableEmulatorRuleTest.java
google-cloud-bigtable-emulator/src/test/java/com/google/cloud/bigtable/emulator/v2/EmulatorTest.java
google-cloud-testing/google-cloud-bigtable-emulator/README.md
pom.xml
versions.txt

It was accidentally moved into its own repo https://github.com/googleapis/java-bigtable-emulator.
This PR copies it back. Git history is short enough that a subtree merge would be over kill.

chore: copy the emulator back into this repo.

---

pom.xml

This should supercedes #15. 
The new shared config force checkstyle checks, unfortunately this doesn't play well with annotations and generated sources as maven will add the generated sources path to `$project.compileSourceRoots`, which checkstyle uses as the default value for `<sourceDirectories>`, this PR changes the value to src/main/java

chore(deps): update google-cloud-shared-config

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/reframing/ReframingResponseObserver.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/gaxx/reframing/ReframingResponseObserverTest.java

This was discovered while debugging another issue. While deflaking
ReadRowRetryTest, this issue came up preventing me from seeing the
underlying issue.
ReframingResponseObserver#deliverUnsafe() should never fail. However if
does, it will try to cancel the upstream stream and notify the
downstream observer. However canceling the upstream can throw an
exception and prevent the downstram observer from being notified of any
error.
This fix will catch cancellation errors and add them as suppressed
exceptions to the original failure

fix: handle recovery failures during stream reframing failure

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/MutationApi.java

For documentation about the timestamp format for Mutation#setCell APIs.

Added note about timestamp granularity in MutationApi interface.

---

google-cloud-bigtable/pom.xml

grpc-alts has a transitive dep on grpc-stub, but our tests have a direct dependency on it. This would cause the transitive dependency to be downgraded to the test scope

fix: use proper scope for DirectPath transitive dependencies

---

google-cloud-bigtable/pom.xml
scripts/setup-test-table.sh

The integration tests in this project can target multiple environments: emulator, cloud, etc. This is implemented using profiles. To avoid conflicts, the summary reports were suffixed by the profile name. Unfortunately the individual test reports were not and each profile would overwrite the previous reports. This PR gives each profile its own directory.
Also, it fixes up the setup script

fix: Prevent integration tests from different profiles from clobbering each other

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsRetryTest.java

This is to prepare for upcoming changes that will move simple retries to gRPC.
When this happens we want to retain retry settings at the client level, so they are copied into the manual settings wrapper.
See cl/277568516 for more details

chore: Ignore gapic settings for all streaming RPCs

---

google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/TestEnvRule.java

* Add fine grained grpc logging for integration tests. These will create a grpc log file per test rule invocation, which is effectively per test class
* To avoid interleaving in the logs, parallelize the tests by class
* Parallelize the unit tests as well

chore: improve tests

---

google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java
pom.xml

* Fix bug in the instance admin IT. This was unnoticed because our presubmits target a development instance (I just changed that)
* Move auto-value back as a provided dep in the main dependency list. This caused issues in intellij when annotation processing was disabled
* Disable concurrent unit tests, it makes the autogen tests flaky

chore: fix tests

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/LargeRowIT.java

The updated version will be run as part of the instance creation test, this will minimize the contention on the shared instance

chore: update  basicClusterOperationTest to be more robust

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/TestEnvRule.java

At some point, the allowed settings were changed from "prod" and "emulator" to "cloud" and "emulator".
This change updates the error message associated to the illegal argument exception.

chore: update Error message for bad bigtable.env variable

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Filters.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java

Added `FILTERS.timestamp().exact()` for better access & read ability.

---

google-cloud-bigtable/pom.xml

It seems like maven will run integration tests w/o a profile under some circumstances. So -Pbigtable-prod-it will still run the emulator integration tests. This PR will explicitly disable default integration tests and enable them in each profile.
Please note that the emulator profile is still active by default, so integration tests will still run

chore: make sure that integration tests only run as part of a profile

---

pom.xml

deps: upgrade gax to 1.52.0, google-cloud-core to 1.92.0

---

google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/misc_utilities/SimpleGceRawRead.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/CloudEnv.java

directpath-bigtable.googleapis.com is now available

chore: use prod endpoint for directpath tests

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/internal/RefreshChannel.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/internal/RefreshChannelTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java

Implement ChannelPrimer to establish connection to the GFE so bigtable client will reconnect to the Cloud Bigtable service periodically before the connection gets terminated.

feat: add experimental channel refreshing

---

README.md
google-cloud-bigtable-deps-bom/README.md
google-cloud-bigtable-deps-bom/pom.xml
google-cloud-bigtable-emulator/pom.xml
google-cloud-bigtable/pom.xml
grpc-google-cloud-bigtable-admin-v2/pom.xml
grpc-google-cloud-bigtable-v2/pom.xml
pom.xml
proto-google-cloud-bigtable-admin-v2/pom.xml
proto-google-cloud-bigtable-v2/pom.xml

Move all of the dependency version management out of the root pom and into a separate BOM.
This will allow java-bigtable-hbase to sync on dependency versions with java-bigtable.
In addition to moving the dependencyManagement section to a BOM, I imported `google-auth-library-bom` and fixed the README to point to the correct version of gRPC

feat: introduce google-cloud-bigtable-deps-bom

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactory.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java

The new factory allows users to construct a single heavy factory object that can create many lightweight clients.
This is meant to be used in situations when a single application needs to access multiple instances or use different application profiles

feat: add BigtableDataClientFactory to create lightweight data clients

---

google-cloud-bigtable-bom/pom.xml
google-cloud-bigtable-deps-bom/pom.xml
google-cloud-bigtable/pom.xml
pom.xml

This is a counter PR for https://github.com/googleapis/java-bigtable/pull/133 that fixes the failsafe config

build(deps): manually update dependency com.google.cloud:google-cloud-shared-config to v0.3.1

---

pom.xml

The checkstyle settings in our pom.xml were added to the shared config and can now be deleted here.
Also some minor whitespace reformatting

chore: remove checkstyle plugin from pom after shared config update

---

google-cloud-bigtable-deps-bom/pom.xml

* expand google-cloud-core to a bom, so that we fix google-cloud-core-http's version in the hbase adapter
* google-http-client-bom, it's a transitive dep for google-cloud-bigtable and a direct dep of the hbase adaptor
* opencensus-* add a bunch more relevant opencensus deps. There is no opencensus-bom, so we enumerate any that might be useful

deps: add a few missing artifacts to the deps bom

---

google-cloud-bigtable-deps-bom/pom.xml

It's not used by this client, but this client uses proto-google-common-protos,
and the hbase adapter uses grpc-google-common-protos. So we will use the deps
bom to align the 2. Ideally we would use google-common-protos-bom, but that doesn't
exists

chore(deps): add grpc-google-common-protos to the deps bom

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Query.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableBulkReadRowsCallSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsBatchingDescriptor.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/BulkReadIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/QueryTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/BigtableBulkReadRowsCallSettingsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsBatchingDescriptorTest.java

Fixes #7 
This change introduces BulkReadAPI on BigtableDataClient. This operation
accepts row keys in a batch mode and behind the scene split them based
on configurable values.

feat: introducing bulk read API through Batcher

---

google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/DirectPathFallbackIT.java

DirectPath requires compute channel credentials. If any other credentials are set, then it will silently fallback to cloud path.  The DirectPathFallbackIT requires the connection to use DirectPath, however kokoro currently configures GOOGLE_APPLICATION_CREDENTIALS for all tests. So this PR forcefully sets the credentials provider to be ComputeEngineCredentials

chore: force compute engine creds for directpath test

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Query.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/QueryTest.java

Currently, bigtable could only serve read row requests with the filter size of 20MB. Adding this check to prevent failure.

chore: add filter size check on read row request

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/ReadIT.java

Fixes #188
Adding a new Row exists() API in `BigtableDataClient`

feat: add row exists api

---

README.md

Fixes #184
This change contains a note for deployment configuration in GKE. If no configuration
is provided the JVM in CoS detects only 1 CPU/Core, which restrains the
the number of channels resulting in performance loss.

docs: readme note for gke deployment configuration

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java

chore: java doc update to for returned data instances

---

google-cloud-bigtable/pom.xml

This should mitigate diamond dependency issues.
Gradle and maven have different behaviors when resolving transitive dependency version conflicts. Gradle selects the greatest version, while maven picks the closest in the dependency hierarchy. For example:
Say http-client and google-auth-library pull in different versions of Apache commons logging at the same depth. Then which one your project gets depends on whether you depend on http-client first and google-auth-library second or vice versa.
This PR enforces that the resolution behavior remains consistent and will break the build.
Fixes issues like googleapis/google-http-java-client#981

chore: ensure that transitive deps have the latest version selected

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java

Should remove this warning:
```
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=12, target=localhost:33848} was not shutdown properly!!! ~*~*~*
Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
```

chore: fix test warnings about unclosed grpc channels

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java

This change is towards the alignment of defaults for HBase over Veneer changes. This commit includes:
- readRows() ->RetrySetting -> maxRetryAttempts -> 10 times
- bulkMutate -> flowController -> maxOutstandingElementCount -> 10L * 100L * channelCount

chore: updated data Stub setting

---

google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java

Fully compose own callable chains. This will remove the need to fiddle with StubSettings
to disable default retry behavior and will also  eliminate unnecessary gapic trace spans. This also fixes a  bug where the trace annotations for ReadRows was missing the connection id. And this will pave the way for decoupling Opencensus via the ApiTracer api

refactor: stop using autogenerated gapic chains

---

.repo-metadata.json
samples/install-without-bom/pom.xml
samples/snapshot/pom.xml
samples/snippets/pom.xml
synth.metadata

This should fix the snippet tags in samples and bump the synth.metadata file so that autosynth can send coherent pull requests again.
* Re-ran synthtool
* Reverted proto/java changes to isolate templates
* Reverted version changes for googleapis in synth.metadata.

chore: fix samples snippets, bump synth.metadata

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/StateMachine.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/StateMachineTest.java

These errors should never happen. But if they do, it would very useful to get more context as to what rows triggered them

feat: add more context to row merging errors

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java

Fixes #275 
This commit would enable the user to target the table using an absolute resource name on each read request. Currently, we expose `ServerStreamingCallable<Query, RowT>`, which does not have an option to provide different `app-profile-id` on each request.

feat: expose new API with ReadRowsRequest in EnhancedBigtableStub

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java

chore(fix): unflake MetricsTracerTest

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/HeadersTest.java

Fix the header added in #268 to the one being used in experiment.

fix: change app_profile_id to the correct header app_profile

---

.github/CODEOWNERS
.repo-metadata.json
synth.metadata

The CODEOWNERS file is now templated so that java-samples-reviewers group can manage samples. Restoring the config for the rest of the code.

chore: specify primary CODEOWNERS team in repo-metadata

---

google-cloud-bigtable-deps-bom/pom.xml
google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/DirectPathFallbackIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java

- Update DirectPath tests to use the new opt-in method instead of env var
- Change fallback tests to blackhole all ipv4 and ipv6 DP addresses
Q: This change depends on v0.8.0 google-cloud-shared-dependencies, so do I need to wait for https://github.com/googleapis/java-bigtable/pull/338 to be merged?

chore: update DirectPath tests

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/internal/NameUtil.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/Backup.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateBackupRequest.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/OptimizeRestoredTableOperationToken.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/RestoreTableRequest.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/RestoredTableResult.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/UpdateBackupRequest.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/stub/EnhancedBigtableTableAdminStub.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/internal/NameUtilTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableBackupIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/BackupTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateBackupRequestTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/RestoreTableRequestTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/UpdateBackupRequestTest.java

feat: Cloud Bigtable Managed Backup Implementation

---

google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/CloudEnv.java

As we are rolling out DirectPath IPv4 support, we want to test both ipv4 and ipv6 cases (i.e. run test client on both ipv4-only VM and ipv6-enabled VM). And to make sure DirectPath is working as expected on both ipv4/ipv6 connection, we would want to introspect the peer IP address after connection is successfully established.
Changes in this PR:
* Added client interceptor in `CloudEnv.java`, which is only enabled for directpath tests. Please advise if there's a better place for adding this interceptor.
* Throws a `RuntimeException` when remote IP address is not as expected.
* Added `bigtable-directpath-ipv4-it` test profile to be run on a ipv4-only VM. The original `bigtable-directpath-it` will still be run on a ipv6-enabled VM.

chore: Introspect peer IP address for directpath tests

---

google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/CloudEnv.java

With the new DNS support, a client running on ipv6-enabled VM could receive both ipv4 and ipv6 balancer addresses. And client could either pick the ipv4 address or the ipv6 address, and different languages of grpc have different behaviors. For Java, it will pick ipv4 address by default, so we should allow that connection when running directpath-ipv6 tests.

chore(fix): directpath ipv4 connection should not fail for an ipv6-enabled test client

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/RowCell.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/RowCellTest.java

fix: RowCells are not actually serializeable

---

google-cloud-bigtable-emulator/src/main/java/com/google/cloud/bigtable/emulator/v2/Emulator.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminSettingsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminSettingsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableBackupIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableTableAdminClientIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/ReadModifyWriteRowTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/EmulatorEnv.java

* Add missing RunWith annotations
* unnecessary downcasts
* Make emulator path overridable

fix(test): Clean up tests

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java

Configure the UserAgent in addition to x-goog-api-client. This will be needed for DirectPath
This depends on #398 for the test changes

feat: include User agent

---

google-cloud-bigtable-emulator/src/main/java/com/google/cloud/bigtable/emulator/v2/Emulator.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java

This will enable to detect the dead peer tcp connection within (10+10) seconds and start a new one. 
Fixes #408 408☕️

feat: add keepalive changes in java client library

---

google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/GoogleUtils.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/main/templates/com/google/cloud/bigtable/Version.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java

The previous approach used the jar manifest. Unfortunately that approaches falls apart when the 
consumer shades the client jar. The new approach uses a combination of releasetool's version tag
replacement and maven-resources-plugin to generate a class with an embedded version string.

chore: make version embedding more robust

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java

Update client to attempt DirectPath by default, and remove DirectPath test endpoint.
Note that it doesn't mean that after this change client will just use DirectPath, but will call the DirectPath codepath by default. 
The actually enablement of DirectPath is controlled by service owner via ACL config. For now, after this change, although all users will attempt DirectPath, but they will all just fallback to the original CFE path.
For testing, we will just use `-Dbigtable.directpath-data-endpoint` and `-Dbigtable.directpath-admin-endpoint` to override the default endpoint with DP enabled endpoints.
@igorbernstein2 
@mgarolera
@mohanli-ml

feat: attemp DirectPath by default

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableBackupIT.java

feat: backup level IAM

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactory.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/FakeServiceHelper.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java

fix: Make refreshing channel compatible with BigtableDataClientFactory

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java

I found that the `readRow` settings were referencing the `baseDefaults` (i.e. the defaults in the GAPIC stub settings) for `readRows`, rather than the manually overridden settings that are used for the `retryableCodes` immediately above. This seems like the safest thing to keep the sources of the RetrySettings all referencing the manually overridden settings.
This will also be necessary for an upcoming config change that will make RPCs configured as non-retryable in the GAPIC to be generated **without** backoff settings (because they are not retryable). @igorbernstein2 this is the change we spoke about.

fix: readRowSettings use manual readRows settings instead of gapic's

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java

Reverts googleapis/java-bigtable#467
After this PR, gax-java relies on `ComputeEngineCredentials` to determine whether the client should use `ComputeEngineChannelBuilder`: https://github.com/googleapis/gax-java/blob/master/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java#L253
However, `ComputeEngineCredentials` has different assumptions than `ComputeEngineChannelBuilder`, which causes `ComputeEngineChannelBuilder` to fail on AppEngine: https://github.com/grpc/grpc-java/issues/7604.
We need to rollback this PR, and make the fix in gax-java, and then roll-forward again.
@apolcyn 
@mohanli-ml 
@igorbernstein2
@mgarolera

Revert "feat: attemp DirectPath by default"

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java

Having keepalive pings at 10s can cause too_many_ping commands and it will double the keepalive time for new connections on that channel.
This PR sets keepalive pings at 30s (allowed by Google Frontends) which will avoid too many pings warnings.
Do not set keepAliveWithoutCalls(true) as enabling keepalive on idle streams can increase load.

fix: make keepalive params a bit conservative

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java

fix: Fix NPE in MetricTracer when MutateRowsRequest is invalid

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsConvertExceptionCallable.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsRetryTest.java

fix: Retry "received rst stream"

---

README.md

docs: Update stackdriver examples for tracing and stats

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableBatchingCallSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataSettingsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/BigtableBatchingCallSettingsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java

Implementation of go/veneer-dynamic-flow-control.
Part 1, add the settings for enabling / disabling dynamic flow control. The settings will later be used in EnhancedBigtableStub, see https://github.com/googleapis/java-bigtable/pull/612 for reference.

feat: dynamic flow control part 1

---

samples/snippets/src/main/java/com/example/bigtable/ConfigureConnectionPool.java
samples/snippets/src/test/java/com/example/bigtable/ConfigureConnectionPoolTest.java

samples: Sample for configuring connection pool

---

.kokoro/nightly/integration.cfg
.kokoro/presubmit/integration.cfg
google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/Backup.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/Cluster.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateClusterRequest.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateInstanceRequest.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/EncryptionInfo.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/common/Status.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableCmekIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/BackupTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/ClusterTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateClusterRequestTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/EncryptionInfoTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/common/StatusTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/CloudEnv.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/EmulatorEnv.java
pom.xml

#673 
All data at rest is typically encrypted with Google's default encryption. This feature will provide support for Customer Managed Encryption Keys (CMEK) in the JAVA client, allowing users to control their encryption keys. CMEK data at rest is protected using an encryption key that users control and manage through Cloud Key Management Service (Cloud KMS).

feat: add CMEK Support 

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableCmekIT.java

move `finally` blocks to `AfterClass`, move instance and table creation to `BeforeClass`
Add additional assertion when failure is expected

test: small refactor to cmek test

---

google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/DirectPathFallbackIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/CloudEnv.java

prod-it - runs connection agnostic integration tests using whatever connection is available
bigtable-directpath-it - runs directpath specific tests and augments the agnostic tests to check that they are running over DirectPath
bigtable-directpath-ipv4only-it - similar to bigtable-directpath-it but checks that connections are made only over ipv4
bigtable-cfe-it - runs connection agnostic tests but augments them to ensure that connections are not made over DirectPath

chore: update DirectPath profiles

---

.kokoro/nightly/integration.cfg
.kokoro/presubmit/integration.cfg
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableCmekIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java

Change-Id: I33491161798816636e3208e14346e880b471b065
We want to work with us-central1-b, us-east1-b & us-east1-c zones specifically for our internal testing. So just changing to a combination that works.
The requisite keys and permissions have been setup already.

test: update zones in cmek test

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableCmekIT.java

Change-Id: Idc8ad885205190374b089349ee94cc627bafd782
Getting an error internally about cluster with clusterId2 already existing. So changing to use new clusterId for the other zone scenario.

fix: change clusterId in Cmek test

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableBatchingCallSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/DynamicFlowControlCallable.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/DynamicFlowControlStats.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracer.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataSettingsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/BulkMutateIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/BigtableBatchingCallSettingsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/DynamicFlowControlCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/DynamicFlowControlStatsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java

feat: dynamic flow control

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/EncryptionInfo.java

The docs were accidentally the same as the previous enum. Corrected to reflect https://github.com/googleapis/java-bigtable/blob/master/proto-google-cloud-bigtable-admin-v2/src/main/proto/google/bigtable/admin/v2/table.proto#L230-L237

fix(docs): correct docs for CUSTOMER_MANAGED_ENCRYPTION

---

google-cloud-bigtable-deps-bom/pom.xml
google-cloud-bigtable/EnableAutoValue.txt
google-cloud-bigtable/pom.xml
pom.xml

google-shared-config already has provisions for autovalue & error_prone. No need for us to track it separately.
This will remove auto-value-annotations from the compile path and into annotation processor path.

chore: remove duplicate deps (error_prone & autovalue) from bigtable specific pom

---

.kokoro/release/publish_javadoc11.sh
pom.xml

Fixes b/179935006
Due to the way v1 html javadocs are currently [configured](https://github.com/googleapis/java-bigtable/blob/master/pom.xml#L206) - we can't produce docs for cloud-rad in exactly the same manner as other java repos. This allows us to generate for cloud-rad (with excluded classes) without changing what we're doing with current doc generation yet.

chore: cloud-rad doc generation

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Query.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/QueryTest.java

Should  be 20 KB not 20 MB
https://cloud.google.com/bigtable/quotas#row-filters

fix: filter limit constant

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableBackupIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableCmekIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableTableAdminClientIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/BulkMutateIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java

* fix resource cleanup: time based resource cleanup expected a prefix followed by a number, but some tests inserted a string in between which would prevent clean. Now all prefixes are generated in a single place
* fix cleanup contention: concurrent tests will try to cleanup resources at the same time. Mitigate this by swallowing not found error
* fix concurrent test runs: the prefix was based on time only, which would causes tests running in the same second to clobber each other
* optimize backup test to only create a single new instance

chore(test): improve resource handling in tests

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableBackupIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableCmekIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableTableAdminClientIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/PrefixGenerator.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/TestEnvRule.java

Follow up to #801
* move prefix generation to its own instance rule
* log whenever a new prefix generated, which should make it easier to debug test failures

chore(test): log resource prefix to make debugging easier

---

.github/release-please.yml

file path was removed in last sp merge. It was pointing to the wrong file https://github.com/googleapis/java-bigtable/blob/1af8925747c22f4e8d50a76dc60f6fafddac20d2/.github/release-please.yml#L4

fix: add back in extraFiles and fix file path

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Query.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/QueryTest.java

* fix: filter limit constant
Should 20 KB not 20 MB
* fix test
(cherry picked from commit 04f8ad463d1fa9efe0ab941ee5f3d0794baed814)

fix: filter limit constant (#787)

---

.github/release-please.yml
google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/Version.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/VersionTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
synth.py

(cherry picked from commit 1af8925)
additional fixing version cherry pick: (cherry picked from commit f914954)

fix: improve embedded version handling (#715)

---

pom.xml

Undo revert, the issue was caused by an old maven version in internal tests which has been updated

Revert "fix: revert conformance test version"

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/PointReadTimeoutCallable.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/PointReadTimeoutCallableTest.java

Special case point reads to use grpc's deadlines instead of relying on the watchdog

feat: promote stream wait timeouts to deadlines for point reads

---

google-cloud-bigtable/clirr-ignored-differences.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/PointReadTimeoutCallable.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/FakeServiceHelper.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/PointReadTimeoutCallableTest.java

This introduces 2 new variants of new*Batcher that accept a GrpcCallContext. This context will be used for batch RPCs generated by the batcher instance.
Also fixes handlings of timeout overrides for point reads and bukmutations. If a user set a timeout, don't override it

feat: all setting timeouts for batchers + fix handling of timeouts for point reads

---

google-cloud-bigtable/clirr-ignored-differences.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/PointReadTimeoutCallable.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/FakeServiceHelper.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/PointReadTimeoutCallableTest.java

Reverts googleapis/java-bigtable#861
Unfortunately this doesnt work. The ServerStreamingAttemptCallable will stamp the total timeout as the timeout on ApiCallContext, which will prevent PointReadCallable from stamping the streamWaitTImeout.

revert: Revert "feat: all setting timeouts for batchers + fix handling of timeouts for point reads"

---

google-cloud-bigtable/clirr-ignored-differences.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/FakeServiceHelper.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java

This unreverts #861 (but without the point read bits)
This introduces 2 new variants of new*Batcher that accept a GrpcCallContext. This context will be used for batch RPCs generated by the batcher instance.
Also fixes handlings of timeout overrides for bukmutations. If a user set a timeout, don't override it

feat: call setting timeouts for batchers

---

google-cloud-bigtable-bom/pom.xml
google-cloud-bigtable-deps-bom/pom.xml

All java client libraries inherit the distributionManagement section form shared-config. To prevent individual pom files from overriding the shared-config version of distributionManagement, it is being removed.

chore: remove distributionManagement section

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/CompositeTracer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/CompositeTracerFactory.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerFactory.java

Extends `BaseApiTracer` and `BaseApiTracerFactory` instead of implementing `ApiTracer` and `ApiTracerFactory` after gax change is picked up. New methods could be added to `ApiTracer` and won't break the client.

chore: use BaseApiTracer and BaseApiTracerFactory

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubCloseRetryTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubCloseTest.java

Previously the client.close() would simply shutdown the channel pool and the executor immediately after. Unfortunately this leads to RPCs that would hang forever because an outstanding RPC didnt have an executor to notify of its completion. This PR ensures that the channels are drained before shutting down the executor

fix: client.close() should wait until the channels are terminated before shutting down the executor

---

google-cloud-bigtable-emulator/pom.xml
google-cloud-bigtable/pom.xml

#939 switch guava from -android to -jre, which replaced the transitive dep checker-compat-qual with checker-qual. This introduced a version conflict between guava's transitive deps and truth's: gauva depends on version 3.8.0 while truth depends on 3.13.0. #939 tried to workaround the conflict by excluding the transitive dep from truth, but it didnt do it all places. This finishes the workaround.
I'm not convinced that this is the correct way to resolve the dependency conflict, but for now this PR just makes it consistent

deps: fix UpperBoundsDep check for checker-qual

---

google-cloud-bigtable/pom.xml

Integration tests started failing due to dependency upper bounds rules. It appears that something is not respecting the wildcard exclusions. For the time being this will explicitly exclude all deps

chore: temporary workaround for maven wildcard excludes

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/MutationTest.java

refactor: Avoid setting empty builders in proto setters

---

google-cloud-bigtable/pom.xml

Reverts googleapis/java-bigtable#985

revert: temporary workaround for maven wildcard excludes

---

google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/TestEnvRule.java

Mucking around with java util logging fails when tests are executed in parallel. 
So make the 2 features exclusive: by default tests are executed in parallel, if verbose logs are needed 
they can be activated by a profile that will disable parallel execution.
Also switch parallel tests to run in threads instead of processes 
and enable parallel execution for unit tests
Fixes #692

fix: parallel execution and verbose grpc logs

---

google-cloud-bigtable/pom.xml

This should've been part of dd5164dc. Maven doesnt automatically plumb maven properties to failsafe tests, so it must be done explicitly

chore: fix grpc logs part 2

---

google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClientTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/stub/AwaitReplicationCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/MutateRowCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsFirstCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsRetryTest.java
pom.xml

update mockito-all to mockito-core and use the latest version

deps: migrate to mockito-core 3.12.4

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsConvertExceptionCallable.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsRetryTest.java

fix: fix typo in rst stream message

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/CompositeTracer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/HeaderTracerStreamingCallable.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/HeaderTracerUnaryCallable.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/RpcViewConstants.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/CompositeTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/HeaderTracerCallableTest.java

Refactor `BigtableTracer` and HeaderTracer callables to include status in the label and add Status label to the GFE metric views.

fix: add status label to gfe metrics

---

google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/MavenPlaceholderShaded.java

Currently javadoc build is failing:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.3.1:jar (attach-javadocs) on project google-cloud-bigtable-stats: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - javadoc: error - No public or protected classes found to document.
```

fix: make placeholder class public

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/CompositeTracer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/RpcMeasureConstants.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/RpcViewConstants.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/RpcViews.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/TracedBatcherUnaryCallable.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/CompositeTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/misc_utilities/MethodComparator.java

`BatcherImpl` will add [throttled time to ApiCallContext](https://github.com/googleapis/gax-java/blob/main/gax/src/main/java/com/google/api/gax/batching/BatcherImpl.java#L277). Get the time from call context and export it to `batch_throttled_time` metric.
(This change depends on new gax release with https://github.com/googleapis/gax-java/pull/1463)

feat: add batch throttled ms metric

---

.kokoro/build.sh
google-cloud-bigtable-emulator/pom.xml

* Bump the version of the google-cloud-gcloud-maven-plugin to fix directory creation
* Remove darn x86 artifact since it's no longer published

chore: fix emulator bundling

---

pom.xml

Reverts googleapis/java-bigtable#1108

fix: Revert "fix: remove stats from javadoc"

---

.kokoro/build.sh
google-cloud-bigtable-emulator/pom.xml

Bump the version of the google-cloud-gcloud-maven-plugin to fix directory creation
Remove darn x86 artifact since it's no longer published
port of #1107

chore: fix emulator bundling for 2.2.x sp

---

.kokoro/build.sh
google-cloud-bigtable-emulator/pom.xml

Bump the version of the google-cloud-gcloud-maven-plugin to fix directory creation
Remove darn x86 artifact since it's no longer published
port of #1107

chore: fix emulator bundling for 1.22.0 sp

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/UpdateAppProfileRequest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/AppProfileTest.java

fix: UpdateAppProfileRequest equals and hashcode should build proto

---

pom.xml

Currently causing https://github.com/googleapis/java-bigtable/pull/1148 to not update all version numbers

build(fix): fix formatting to update versions properly

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/DirectPathFallbackIT.java

The ComputeEngineChannelBuilder layer no longer exists and thus should be removed.
This can only be tested by running kokoro test on GCE. Local IT tests pass but can't prove that this is going to fix it in kokoro.

chore(test): fix api breakage in DirectPath integration tests

---

README.md
samples/native-image-sample/README.md
samples/native-image-sample/pom.xml
samples/native-image-sample/src/main/java/com/example/bigtable/NativeImageBigtableSample.java
samples/native-image-sample/src/test/java/com/example/bigtable/NativeImageBigtableTest.java
samples/pom.xml

This PR copies over the sample for native image support in Bigtable from the [old native image support repo](https://github.com/GoogleCloudPlatform/native-image-support-java/tree/master/native-image-samples/native-image-samples-client-library/bigtable-sample). 
Some things to note:
1. This PR slightly modifies the sample code to be more test-friendly.
2. It also adds an integration test that can be run as a native image. 
Calling `mvn package -Pnative` in the `native-image-sample` directory  builds the native image for the application and calling `mvn test -Pnative` runs the test as a native image.
For more information: https://graalvm.github.io/native-build-tools/latest/maven-plugin.html#configuration

docs(sample): Add sample for native image support in Bigtable

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/internal/RowSetUtil.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/internal/RowSetUtilTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/QueryTest.java

RowSetUtil has 2 methods to split a RowSet: split and shard.
Split is used for ReadRows resumption, so the split needs to be included in the segment.
Shard is used for map/reduce style frameworks to parallelize the work. In this case the split points should be treated as start keys (since they usually come from SampleRowKeys and align with the start of a tablet. This PR fixes the shard behavior to use splits as start keys. It introduces some code duplication but overall makes it easier to reason about the 2 behaviors

chore: update rowset sharding to use split points as start keys

---

.repo-metadata.json
google-cloud-bigtable-bom/pom.xml
google-cloud-bigtable-emulator-core/pom.xml
google-cloud-bigtable-emulator-core/src/main/java/com/google/cloud/bigtable/emulator/core/EmulatorController.java
google-cloud-bigtable-emulator/pom.xml
google-cloud-bigtable-emulator/src/main/java/com/google/cloud/bigtable/emulator/v2/Emulator.java
pom.xml
versions.txt

Currently the emulator exists in a single artifact with optional deps. The reason for this is that bigtable-hbase needs the emulator w/o grpc. However this is causing issues in graalvm packaging in #1234. This PR makes this easier to manage: a -core artifact without dependencies that just wraps the golang binary that bigtable-hbase can use and a wrapper that has a hard dep on grpc & gax.
This is technically a breaking change but the emulator artifact is pre-GA an is marked with BetaApi
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.m …

feat: split emulator into core without deps and a higher level wrapper with grpc helpers

---

pom.xml

fix: remove the shaded profile from root pom

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamContinuationToken.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamRecord.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/CloseStream.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Heartbeat.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/ReadChangeStreamQuery.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamRecordTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/ReadChangeStreamQueryTest.java

1. ReadChangeStreamQuery will be used by readChangeStream(TODO).
2. ChangeStreamRecord is one of: Heartbeat, CloseStream, or ChangeStreamMutation(TODO). It will be used as the return type for readChangeStream.

feat: Create ReadChangeStreamQuery and ChangeStreamRecode::Heartbeat/CloseStream

---

google-cloud-bigtable/clirr-ignored-differences.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/ConvertExceptionCallable.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsRetryTest.java

fix: retry rst stream in mutations

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamMutation.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/DeleteCells.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/DeleteFamily.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Entry.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Heartbeat.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/SetCell.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamMutationTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamRecordTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/EntryTest.java

A ChangeStreamMutation holds a list of mods, represented by List<Entry>,
where an Entry is one of DeleteFamily/DeleteCells/SetCell.

feat: Add ChangeStreamMutation which is a ChangeStreamRecord

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamMutation.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamRecordAdapter.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/DefaultChangeStreamRecordAdapter.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Heartbeat.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/changestream/ChangeStreamStateMachine.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamMutationTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/DefaultChangeStreamRecordAdapterTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/changestream/ChangeStreamStateMachineTest.java

These will be used later for ChangeStreamMergingCallable.

feat: Add ChangeStreamRecordAdapter and ChangeStreamStateMachine

---

README.md
google-cloud-bigtable/pom.xml

Fixing similar issues as googleapis/java-pubsub#1239. The test-scope were recently added https://github.com/googleapis/java-bigtable/pull/1336/files

fix: declaring 2 http libraries as runtime

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamContinuationToken.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamMutation.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/CloseStream.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Heartbeat.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamContinuationTokenTest.java

This will be used by the beam connector to write/read to a Bigtable table.
This PR also does:
1. Changs `ChangeStreamContinuationToken` to hold a proto instead of a builder
since it's a response type.
2. Revert the changes in https://github.com/googleapis/java-bigtable/pull/1345
since we can use Mockito to create mock objects for testing.

feat: Add toByteString/fromByteString for ChangeStreamContinuationToken

---

.readme-partials.yml
README.md

chore: add instructions to enable builtin metrics

---

README.md
google-cloud-bigtable-bom/pom.xml
google-cloud-bigtable-deps-bom/pom.xml
google-cloud-bigtable-stats/pom.xml
google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/BigtableCreateTimeSeriesExporter.java
google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/BuiltinMetricsIT.java
pom.xml

test: add integration test for builtin metrics

---

google-cloud-bigtable-stats/clirr-ignored-differences.xml
google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/StatsRecorderWrapper.java
google-cloud-bigtable-stats/src/test/java/com/google/cloud/bigtable/stats/StatsRecorderWrapperTest.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracer.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracerTest.java

fix: reset a measure map everytime the stats are recorded

---

google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/BigtableStackdriverExportUtils.java

The jvmName when calling from cloud function will always be 1@localhost. Add a UUID in the default task value string so we won't have multiple tasks writing to the same stream.

fix: add a UUID in the task value

---

README.md
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Mutation.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/RowMutationEntry.java

feat: add apis for Mutation and RowMutationEntry

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracer.java

We need to fix: https://github.com/googleapis/gax-java/blob/11c4a7caf31de256f29678de829f11f9558adcfd/gax/src/main/java/com/google/api/gax/rpc/ServerStreamingAttemptCallable.java#L379

fix: fix attempt status tag for metrics

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracerTest.java

fix: set a longer timeout to wait for callbacks to be executed

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracerStreamingCallable.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracerUnaryCallable.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/Util.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracerTest.java

fix: fix the connectivity error count caculation

---

.github/workflows/ci.yaml

As seen in https://github.com/googleapis/java-bigtable/pull/1497, unit tests (11) gets cancelled if unit tests (7) fails. This PR prevents workflows from getting cancelled at the first failed job.

chore: turn off fail-fast behavior to prevent cancellation of jobs

---

.github/release-please.yml
.github/sync-repo-settings.yaml

feat: next release from main branch is 2.17.0

---

README.md
test-proxy/EnableAutoValue.txt
test-proxy/README.md
test-proxy/pom.xml
test-proxy/src/main/java/com/google/cloud/bigtable/testproxy/CbtTestProxy.java
test-proxy/src/main/java/com/google/cloud/bigtable/testproxy/CbtTestProxyMain.java
test-proxy/src/main/proto/v2_test_proxy.proto

feat: add test proxy to java-bigtable client

---

test-proxy/src/main/java/com/google/cloud/bigtable/testproxy/CbtTestProxy.java
test-proxy/src/main/proto/v2_test_proxy.proto

This change makes the test proxy work with the hermetic testing that exercises app_profile_id and emulator (https://github.com/googleapis/cloud-bigtable-clients-test)

test(fix): update the test proxy to set app profile id and connect to emulator correctly

---

README.md
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Query.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/QueryTest.java

feat: add a query paginator

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/RestoreTableRequest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTests.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/RestoreTableRequestTest.java

feat: implement cross-project table restore

---

test-proxy/README.md
test-proxy/pom.xml

…so correct the README about building an old version

test(fix): update the test proxy's pom file to build a shaded jar, also correct the README about building an old version

---

README.md
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableChannelPrimer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataSettingsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubCloseTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/HeadersTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsRetryTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsRetryTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/CloudEnv.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/EmulatorEnv.java

feat: enable channel priming by default

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java

Will fix https://github.com/googleapis/java-bigtable-hbase/issues/3518

fix: defer instance admin api errors to RPC time rather then client construction time

---

README.md
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/BuiltinMetricsIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/UnaryMetricsMetadataIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/DynamicFlowControlCallableTest.java

UnaryMetricsMetadataIT: testFailure sometimes fails with:
```
expected to contain: unspecified
but was            : []
```
Setting a longer wait time before checking opencensus stats. Also assign the returned value to a future. 
DynamicFlowControlCallableTest sometimes fails with:
```
value of: getLastAdjustedTimestampMs()
expected: 0
but was : 1669306507692
at com.google.cloud.bigtable.data.v2.stub.DynamicFlowControlCallableTest.testLatenciesAreRecorded(DynamicFlowControlCallableTest.java:105)
```
Cleanup DyanmicFlowControlStats after each test, and create a new Stats instance and callable inside the testLatenciesAreRecorded test.

test: attempt to fix flaky test

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java

Fixes rendering of https://cloud.google.com/java/docs/reference/google-cloud-bigtable/latest/com.google.cloud.bigtable.admin.v2.BigtableTableAdminClient#com_google_cloud_bigtable_admin_v2_BigtableTableAdminClient_awaitOptimizeRestoredTableAsync_com_google_cloud_bigtable_admin_v2_models_OptimizeRestoredTableOperationToken_

docs: fix javadoc code example for awaitOptimizeRestoredTableAsync

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracer.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracerTest.java

fix: fix connectivity error count calculation

---

google-cloud-bigtable/clirr-ignored-differences.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/common/Status.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamMutation.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamRecordAdapter.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/CloseStream.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/DefaultChangeStreamRecordAdapter.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Heartbeat.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/ReadChangeStreamQuery.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/changestream/ChangeStreamStateMachine.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/common/StatusTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamMutationTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamRecordTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/DefaultChangeStreamRecordAdapterTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/ReadChangeStreamQueryTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/changestream/ChangeStreamRecordMergingCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/changestream/ReadChangeStreamMergingAcceptanceTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/changestream/ReadChangeStreamRetryTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/changestream/ReadChangeStreamUserCallableTest.java

Use org.threeten.bp.Instant for below fields:
- startTime
- endTime
- commitTimestamp
- estimatedLowWatermark
Use bigtable.common.Status for CloseStream::getStatus()

fix: Change types for Cloud Bigtable Changestream methods

---

google-cloud-bigtable-deps-bom/pom.xml
google-cloud-bigtable/pom.xml

This is a temporary manual update of dependencies until https://github.com/googleapis/java-bigtable/pull/1640 is merged

deps: update shared deps to 3.3.0 and monitoring to 3.12.0

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/CloseStream.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamRecordTest.java

Do not enforce new_partitions and change_stream_continuation_tokens to be the same size if new_partitions has size of 0 because Cloud Bigtable backend may not be updated to serve new_partitions field yet.
`new_partitions` is a new field and the backend may not be serving this field.
Change-Id: Id21c293b92c304f05b905ca8e8b3988b9241866e

fix: if new_partitions is size 0, do not enforce size check

---

README.md
google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/BigtableCreateTimeSeriesExporter.java
google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/BuiltinMetricsIT.java

test(fix): Run tests in different processes and pull metrics for 10 minutes

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamRecord.java

Make ChangeStreamRecord interface Serializable so that beam can create Coders for it by default.  ChangeStreamMutation, CloseStream, and Heartbeat all already implement Serializable.

fix: Make ChangeStreamRecord interface serializable

---

google-cloud-bigtable-deps-bom/pom.xml
google-cloud-bigtable/pom.xml

https://github.com/googleapis/java-bigtable/pull/1640 doesn't seem to be working to pick up the grpc version. In the meantime, manually update these deps

deps: upgrade shared dependencies to 3.6.0 and monitoring to 3.15.0

---

.github/workflows/conformance.yaml
.kokoro/conformance.sh
test-proxy/known_failures.txt

test(fix): add conformance test to the CI pipeline (redo of PR#1698).

---

google-cloud-bigtable/pom.xml

deps: upgrade maven-enforcer-plugin to 3.3.0, remove duplicate entry in pom

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/RateLimitingServerStreamingCallable.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/RateLimitingCallableTest.java

feat: add rate limiting callable

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java

docs: clean up BetaApi annotations from built in metrics API

---

samples/snippets/src/main/java/com/example/bigtable/Filters.java
samples/snippets/src/test/java/com/example/bigtable/FiltersTest.java

1. Add a filter snippet to read row using a filter
2. Add region tags to two existing snippets

docs(samples): add bigtable filter snippet

---

renovate.json

This was done before we removed the enforcer check, so it is no longer required. Additionally, it's causing PRs which update shared dependencies to have a `test(deps)` prefix rather than `deps`. Example: https://github.com/googleapis/java-bigtable/pull/1755

chore: remove renovate grouping for test protoc and grpc dependencies

---

samples/snippets/src/main/java/com/example/bigtable/HelloWorld.java

Remove multiple client initializations as the snippets are not used standalone

docs(samples): remove client initialization

---

README.md
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java

fix: set wait timeout and update default attempt timeout to 30 minutes

---

google-cloud-bigtable-deps-bom/pom.xml
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/HeadersTest.java

deps: update shared dependencies to 3.11.0

---

google-cloud-bigtable-deps-bom/pom.xml
renovate.json

Opening in favor of #1805 and #1806 which need to be updated together (otherwise the dependency check will fail). Adding this to the renovate config so it will be combined in one PR going forward.

deps: update shared dependencies to 3.12.0, monitoring to 3.21.0, update renovate config

---

google-cloud-bigtable/clirr-ignored-differences.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/internal/RowMergerUtil.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/internal/RowSetUtil.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Query.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsResumptionStrategy.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/RowMerger.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/RowMergingCallable.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/StateMachine.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/internal/RowSetUtilTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/ReadIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/QueryTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/StateMachineTest.java
samples/snippets/src/main/java/com/example/bigtable/Reads.java
samples/snippets/src/test/java/com/example/bigtable/ReadsTest.java

This adds a reversed boolean to Query, which will allow endusers to stream rows in reverse order.
Example:
```java
Query query = Query.create("alphabet").range("a", "z").limit(3);
ServerStream<Row> results = client.readRows(query);
for (Row row : results) {
System.out.println(row.getKey().toStringUtf8());
}
// Prints z, y, x
```

feat: reverse scans public preview

---

pom.xml

The undefined variable in the external link configuration
fails JDK 17 builds.

fix: remove javadoc external link configuration

---

README.md
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateTableRequest.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/Table.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/UpdateTableRequest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTests.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableTableAdminClientIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateTableRequestTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/UpdateTableRequestTest.java

Follow up to https://github.com/googleapis/java-bigtable/pull/1821 adding update table support.

feat: change stream retention to create and update table

---

.github/workflows/ci.yaml
.github/workflows/conformance.yaml

Configures CI for branch
```
release-brancher create-pull-request \
--branch-name="2.23.x" \
--target-tag="v2.23.3" \
--repo="googleapis/java-bigtable" \
--pull-request-title="chore: setup 2.23.x lts branch" \
--release-type=java-backport
```

ci: configure the protected branch

---

pom.xml

The undefined variable in the external link configuration fails JDK 17 builds.
cherry pick of #1815

fix: remove javadoc external link configuration (#1815)

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracerCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/SimpleStatsComponent.java

This fixes a few flaky unit tests that relied on `Thread.sleep` to ensure that all metrics processing was done.  Rather than using `Thread.sleep`, we can instead use an inline event queue in the OpenCensus stats component to execute all work inline, removing the need to wait for anything to finish.

chore: Fix flaky metrics tests

---

.github/release-please.yml
.github/sync-repo-settings.yaml

feat: setup 2.25.x lts branch

---

.github/release-please.yml
.github/sync-repo-settings.yaml
README.md

chore: Revert "chore: setup 2.23.x lts branch (#1852)"

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracer.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/StatsTestUtils.java

This should improve reporting of latency when bulk mutation throttling is enabled. Also:
- fix tests to properly close the batcher
- simplify tests to avoid unnecessary mocking
- improve test failure messaging
Change-Id: I53748c5e54ebbbe2a896f8ea0ce6c39a8f5fa297

fix: aggregate batching throttling latency per attempt and reset it between

---

pom.xml

As part of testing javadoc generation at time of libraries-bom publishing with a specific doclet version, we need a way to override the doclet path currently set in `docFX` profile. This update sets the default `docletPath` to the existing version, and enables an overridden path.

build: update docFX profile to enable overriding doclet path

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/RateLimitingServerStreamingCallable.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/RateLimitingCallableTest.java

Change-Id: I690c522aebea03a966155d930bff26042d1bb1f1

fix: make sure to propagate the response when throttling is enabled

---

README.md
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracerCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/StatsHeadersCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsRetryTest.java

Add a fail safe that marks missing entries in a response as permanent errors. Previously the client assumed that all entries were present and only looked for errors
Change-Id: Ie3f294fd6bb19ec17662b58bfe9c75a3eed81097

fix: check that all bulk mutation entries are accounted for

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracerCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/StatsHeadersCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsRetryTest.java

fix: check that all bulk mutation entries are accounted for (#1907)

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/reframing/ReframingResponseObserver.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/gaxx/reframing/ReframingResponseObserverTest.java

This would manifest as a hang when iterating over a ServerStream from ReadRows
Change-Id: I74533c6714b40a68ec0ef81dadac747e10bee39d

fix: a rare race condition in the row merger

---

grpc-google-cloud-bigtable-admin-v2/pom.xml
grpc-google-cloud-bigtable-v2/pom.xml
pom.xml

The maven-javadoc-plugin version is defined in the shared config pom.xml.
https://github.com/googleapis/java-shared-config/blob/778a547a09de71dbf9e5a42b155f12d15c319864/pom.xml#L472
The removal of the 4 lines corresponds to the lines touched by the recent RenovateBot: https://github.com/googleapis/java-bigtable/pull/1924/files

build: do not declare javadoc plugin version

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
owlbot.py

chore: update contributing doc

---

README.md
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/AppProfile.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateAppProfileRequest.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/UpdateAppProfileRequest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClientTests.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/AppProfileTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateAppProfileRequestTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/UpdateAppProfileRequestTest.java

feat: Add APIs to enable request priorities

---

README.md
samples/native-image-sample/pom.xml
samples/snippets/pom.xml

Somehow the RenovateBot stopped working for libraries-bom
in this repository. Troubleshooting:
https://github.com/googleapis/synthtool/issues/1844
Followed https://github.com/googleapis/java-bigtable/pull/1868/files to locate the files.

chore(deps): manually updating the Libraries BOM

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Query.java

chore: Add getPageSize() to QueryPaginator

---

.github/release-please.yml
.github/sync-repo-settings.yaml

java-bigtable-hbase 2.9.x depends on 2.23.x: https://github.com/googleapis/java-bigtable-hbase/blob/2.9.x/pom.xml#L59.

chore: set up 2.23.x branch

---

README.md
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/reframing/ReframingResponseObserver.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/gaxx/reframing/ReframingResponseObserverTest.java

* fix: a rare race condition in the row merger
This would manifest as a hang when iterating over a ServerStream from ReadRows
Change-Id: I74533c6714b40a68ec0ef81dadac747e10bee39d
* 🦉 Updates from OwlBot post-processor
See https://github.com/googleapis/repo-automation-bots/blob/main/packages/owl-bot/README.md
---------

fix: a rare race condition in the row merger (#1939)

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracerCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/SimpleStatsComponent.java

Cherry pick the flaky test fix so release tests can pass.
This fixes a few flaky unit tests that relied on `Thread.sleep` to ensure that all metrics processing was done.  Rather than using `Thread.sleep`, we can instead use an inline event queue in the OpenCensus stats component to execute all work inline, removing the need to wait for anything to finish.

chore: Fix flaky metrics tests (#1865)

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/CookiesHolder.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/ReadIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/CookiesHolderTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java

Test and rollback plan: [go/cbt-routing-cookie-rollback](http://goto.google.com/cbt-routing-cookie-rollback)

feat: add a flag to add / remove routing cookie from callable chain

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/StateMachine.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/functional/ReadRowsTest.java

Currently they dont have a status associated and thus get counted as UNKOWN
Change-Id: Ida3470a0609f2e2ad51534eb3141db394af1dcdc

feat: count row merging errors as internal errors

---

.github/workflows/unmanaged_dependency_check.yaml
proto-google-cloud-bigtable-v2/pom.xml

In this PR:
- Add an unmanaged dependency check to verify there's no dependency that is not covered by java shared dependencies (the latest [released](https://central.sonatype.com/artifact/com.google.cloud/google-cloud-shared-dependencies) version in Maven Central).
When it fails, this throws error:
```
This pull request seems to add new third-party dependency, [com.h2database:h2], among the artifacts listed in google-cloud-bigtable-bom/pom.xml.
Please see go/cloud-sdk-java-dependency-governance.
```

chore: add an unmanaged dependency check

---

README.md
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java

test: Add a missing @Test annotation

---

.kokoro/presubmit/graalvm-native-17.cfg
.kokoro/presubmit/graalvm-native.cfg
google-cloud-bigtable-bom/pom.xml
google-cloud-bigtable-deps-bom/pom.xml

Notable Changes:
1) Use `gcr.io/cloud-devrel-public-resources/graalvm_sdk_platform*` docker images for Kokoro GraalVM tests  instead of `gcr.io/cloud-devrel-kokoro-resources/graalvm*`.
2) Use `com.google.cloud:sdk-platform-java-config` as the parent which inherits configs from `java-shared-config` and hosts the `google-cloud-shared-dependencies` version under the `google-cloud-shared-dependencies.version` property.  This artifact is versioned to be the same as google-cloud-shared-dependencies.
3) Adjust renovate-bot settings to update docker images when a new version of `sdk-platfrom-java-config` is on Maven Central. 
Example renovate-bot update PR in google-cloud-java: https://github.com/googleapis/google-cloud-java/pull/10290

chore: use sdk-platform-java-config to consolidate build configs

---

google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/BuiltinMeasureConstants.java
google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/BuiltinViewConstants.java

feat: Define the metrics for collecting per connection error count.

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableBackupIT.java

test(fix): Deflake Backup integration tests due to deleteBackup timeouts

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactory.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracerCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java

chore: refactor TracerFactory creation

---

google-cloud-bigtable-deps-bom/pom.xml
google-cloud-bigtable-stats/pom.xml
google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/BigtableCreateTimeSeriesExporter.java
google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/BigtableStackdriverExportUtils.java
google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/BigtableStackdriverStatsExporter.java
google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/BuiltinViewConstants.java
google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/BuiltinViews.java
google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/ConsumerEnvironmentUtils.java
google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/StatsWrapper.java
google-cloud-bigtable-stats/src/test/java/com/google/cloud/bigtable/stats/BigtableCreateTimeSeriesExporterTest.java
google-cloud-bigtable-stats/src/test/java/com/google/cloud/bigtable/stats/ITBuiltinViewConstantsTest.java

feat: add the export logic for per-connection error rate metric

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/RetryInfoTest.java

test: fix flaky vip_java_bigtable test

---

samples/snippets/src/main/java/com/example/bigtable/WriteBatch.java

samples: Update WriteBatch sample to use a batcher

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java

Change-Id: I24a416366207f0154befec267bc74a722a0e4944

chore: format mutate rows impl to be side by side

---

google-cloud-bigtable/clirr-ignored-differences.xml
google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactory.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsConstants.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsView.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/CustomOpenTelemetryMetricsProvider.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/DefaultMetricsProvider.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/ErrorCountPerConnectionMetricTracker.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracerCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/ErrorCountPerConnectionTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java

feat: migrate per connection error count metric to otel

---

google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/BigtableCreateTimeSeriesExporter.java
google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/BigtableStackdriverExportUtils.java
google-cloud-bigtable-stats/src/test/java/com/google/cloud/bigtable/stats/BigtableCreateTimeSeriesExporterTest.java

Fix an issue in exporting per-connection metrics when using a different Bigtable project.

fix: per-connection metrics issue when using a different Bigtable project

---

google-cloud-bigtable/clirr-ignored-differences.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/ColumnFamily.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateTableRequest.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/ModifyColumnFamiliesRequest.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/Type.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/AddToCell.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamMutation.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamRecordAdapter.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/DefaultChangeStreamRecordAdapter.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Mutation.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/MutationApi.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/RowMutation.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/RowMutationEntry.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Value.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/changestream/ChangeStreamStateMachine.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTests.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/TypeProtos.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateTableRequestTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/TableAdminRequestsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/TypeTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamMutationTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/MutationTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/ValueTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/MutateRowCallableTest.java

This PR adds support for type and aggregate APIs to the java client.  Bigtable aggregates will allow users to configure column families whose cells accumulate values via an aggregation function rather than simply overwrite them.
Change-Id: I5882459c862cc1deda11606e181cee38ac4d9099

feat: Add support for type and aggregate APIs

---

.github/trusted-contribution.yml
owlbot.py

A pull request in trusted-contribution bot: https://github.com/googleapis/repo-automation-bots/pull/1682
This is an experiment to try the capability of trusted-contribution bot. This may turn the kokoro labels off. In that case, I'll update another CL to remove the lines.

ci: adding gcbrun for trusted bots

---

README.md
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/RetryInfoTest.java

test: add a test to ensure new methods are tested for RetryInfo

---

.repo-metadata.json
README.md

Adds a field for recommended_package as part of the revamped Library Overviews.
See go/cloud-rad-overviews-handwritten-repos for more details

chore: include recommended_package in repo-metadata.json

---

samples/install-without-bom/pom.xml

This automatically gets incremented after the release is complete by a renovate bot PR (example https://github.com/googleapis/java-bigtable/pull/2173), so no need to increment it here.

chore: remove release-please version increment in samples

---

README.md
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporterTest.java

This fixes and issue with exporting client-side metrics when having too many distinct resources, resulting in batch sizes higher than 200.

fix: batch time series data when exporting client-side metric

---

README.md
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/ConvertExceptionCallable.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/ConvertExceptionCallableTest.java

Change-Id: I3939a89d40ecd4304bccaf0340fe169d6a083712

fix: retry INTERNAL retriable auth errors

---

.github/trusted-contribution.yml

From reading the configuration (https://github.com/googleapis/repo-automation-bots/pull/1682/files), it accepts multiple objects.

ci: automatic kokoro label in addition to /gcbrun comment

---

README.md
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java

Adds a duplicate `getServiceName()` implementation to EnhancedBigTableStubSettings. This is similar to https://github.com/googleapis/java-bigtable/blob/de639bc7869dc5a25029367b8fc470fcd089667d/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableStubSettings.java#L171-L174, but is re-implemented as EnhancedBigTableStubSettings does not implement BigtableStubSettings

fix: Add getServiceName() to EnhancedBigTableStubSettings

---

README.md
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/BuiltinMetricsIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTestUtils.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/ErrorCountPerConnectionTest.java

There is a race condition between publishing metrics and reading them. This PR adds a small retry/sleep loop to poll for absent metrics

test: deflake metrics unit tests

---

google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/ErrorCountPerConnectionTest.java
google-cloud-bigtable/src/test/resources/logging.properties
pom.xml

test: reduce test noise

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/DynamicFlowControlCallableTest.java

Change-Id: I222078817739f8190faefffe405bd01af9c96df9

test: deflake flow control test

---

README.md
samples/snippets/src/test/java/com/example/bigtable/deletes/DeletesTest.java

The test was broken in #2170 which added a new column family. The test was relient on the abolute column family count of the schema. This PR fixes the test by making it focus on the family its trying to delete instead of the entire schema
Change-Id: I0df90e68c0b25c4e66ed7d8ae1c19ae53577443b

test: fix samples test that was broken by a test harness change

---

README.md
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/internal/AbstractProtoStructReader.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/sql/Statement.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/internal/AbstractProtoStructReaderTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/sql/StatementTest.java

Also fixes a bug with float32 lists where it was incorrectly converted to List of Double where we expect List of Float
Change-Id: I4d4b32dcddef74711eeea8997b020c46eee8be3c

feat: Support float32, float64, and array type query params

---

README.md
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java

Copying over from: https://github.com/googleapis/java-bigtable/pull/2012
Bigtable already sets the flag to allow non-default SA in DirectPath on the service side, we also need to set the option on the client side to make this feature work.
Related Spanner PR: https://github.com/googleapis/java-spanner/pull/2635.

feat: allow non default service account in DirectPath

---

.github/workflows/hermetic_library_generation.yaml
README.md

Thanks to @diogoteles08 for the inspection on our repos. This PR inlines environment variables to avoid overriding script injections.

chore: secure hermetic_library_generation workflow

---

.github/workflows/hermetic_library_generation.yaml
generation_config.yaml

In this PR:
- Add generator version to generation config.
The library generation job failed due to config doesn't have a generator version, see https://github.com/googleapis/java-bigtable/actions/runs/10712723965/job/29703584291.

chore: add generator version to config

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/Backup.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateBackupRequest.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/UpdateBackupRequest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTests.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableBackupIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/BackupTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateBackupRequestTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/UpdateBackupRequestTest.java

feat: Add APIs to enable hot backups

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/sql/ExecuteQueryCallableTest.java

fix: pass deadline through ExecuteQuery RetrySettings

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/sql/ExecuteQueryCallableTest.java

fix: time based flakiness in execute query deadline test

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/CookiesHolderTest.java

- stop returning protos to trigger headers
- fix thread safety for variables that are accessed by multiple threads
Change-Id: Ib34440d2ffeddcb5611b5e1cee183004bafc9449

test: clean up CookieHolderTest

---

google-cloud-bigtable/clirr-ignored-differences.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactory.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsView.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/DefaultMetricsProvider.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/BuiltinMetricsIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java

fix: support override monitoring endpoint

---

README.md
google-cloud-bigtable-deps-bom/pom.xml
pom.xml

grpc-java 1.68.0 was a mistake:
https://github.com/grpc/grpc-java/releases/tag/v1.68.0
This PR will temporarily rollback grpc version to 1.67.1 until the shared config is caught up

deps: downgrade grpc to 1.67.1

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableGrpcStreamTracer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/CompositeTracer.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/CompositeTracerTest.java

fix: fix client blocking latency

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/SafeResponseObserver.java

chore: improve logging in safe response observer

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/sql/ExecuteQueryCallableTest.java

Make sure to close the ephemeral stubs to avoid polluting the logs with unclosed channel errors

chore(test): remove some warnings from tests

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableUnaryOperationCallable.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/CompositeTracer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracer.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/BigtableUnaryOperationCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/SkipTrailersTest.java

This is off by default and can be enabled using an environment variable.
When enabled, BigtableUnaryOperationCallable will resolve the user visible future immediately when a response is available and will tell metrics to freeze all timers. Metrics will still wait for the trailers in the background for necessary metadata to publish the frozen timer values.

feat: add an experimental feature to skip waiting for trailers for unary ops

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java

This should save ~300-500u for readRow calls
Change-Id: Idcf531e2db0e9c751c87f3522c8a2ad4733923d6

feat: enable trailer optimization by default

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java

Attempt to fix a flaky java-bigtable Kokoro test with the approach proposed in b/369770575.
Change-Id: Ia8bc9aa98922a226b84c19400dac91db05b0c6c8

test: fix flaky BigtableInstanceAdminClientIT.createClusterWithAutoscalingAndPartialUpdateTest

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactory.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableClientContext.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/DefaultMetricsProvider.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracerCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java

Refactor ClientContext creation.
We need to create OpenTelemetry before client context is created so we can inject the PerConnectionErrorTracker interceptor on the ManagedChannel.
We need to access the open telemetry instance later when we create the TracerFactory.
This PR creates a new BigtableCleintContext class that wraps gax ClientContext and OpenTelemetry so we can access both later to avoid creating a global open telemetry instance.
Also moved client context creation logic from EnhancedBigtableStub to BigtableClientContext.

chore: refactor to wrap client context in BigtableClientContext

---

google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableChannelPrimer.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableClientContext.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/BigtableChannelPrimerTest.java

Send priming requests on the channel instead of using the stub. This means that we'll not collect metrics on ping and warm requests.
Fixes #2371 ☕️

fix: send priming requests on the channel directly

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java

Change-Id: I7d8ac74eae66d34de453b0cd799f45474d6ff0f7

test: add test to ensure that feature flags are sent during a ping and warm rpc

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/AppProfile.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClientTests.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/AppProfileTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateAppProfileRequestTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/UpdateAppProfileRequestTest.java

feat: add support for Row Affinity app profiles

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableExporterUtils.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporterTest.java

fix: move resource detection to the first export to avoid slow start

---

test-proxy/src/main/java/com/google/cloud/bigtable/testproxy/CbtTestProxy.java

This is blocked on https://github.com/googleapis/cloud-bigtable-clients-test/pull/224.

test: do not override status for mutate rows

---

.kokoro/conformance.sh
test-proxy/known_failures.txt

2 new flags were added to `[cloud-bigtable-clients-test](https://github.com/googleapis/cloud-bigtable-clients-test)` when it upgraded `cloud.google.com/go/bigtable` from 1.33 to 1.34: https://github.com/googleapis/googleapis/commit/ab2ad69473e17b813f5555a44b89691f67b66297
This change skips the tests for those 2 flags

fix: Add known conformance test failures

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableStreamResumptionStrategy.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsResumptionStrategy.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/retrying/ServerStreamingAttemptCallable.java

Extend resumption strategy so it also process errors for resumption.

chore: extend resumption strategy

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java

feat(large-row-skip): added large-row-skip-callable with configurable rowadapter

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/FakeServiceBuilder.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/StatsHeadersCallableTest.java

Change-Id: Iad86b73ed68d026097a7cbbb65b3e968b9323203

test: try to deflake BuiltinMetricsTracerTest

---

google-cloud-bigtable/clirr-ignored-differences.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableExporterUtils.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsView.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/DynamicFlowControlCallableTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporterTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsRetryTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsRetryTest.java

This is necessary to unblock upcoming changes that will track additional metrics and a new unified BigtableClient monitored resource.
The primary change was to extract metric data creation from BigtableCloudMonitoringExporter into TimeSeriesConverter. This removes the code duplication in exportBigtableResourceMetrics & exportApplicationResourceMetrics. But more importantly it allows us to have to 2 separate instances of BigtableCloudMonitoringExporter - one for internal metrics and another for public metrics. This will be needed in follow up PRs that will change the monitored resource that internal metrics use - the new monitored resource is incompatible CustomOpenTelemetryMetricsProvider that is needed for public metrics
Change-Id: I3a051f1faccaba1fc17e4151d1ed85ff8e5952f6
Thank you for …

chore: use 2 different exporter instances for internal and external metrics

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/sql/PlanRefreshingCallable.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/sql/PlanRefreshingCallableTest.java

Change-Id: I76d99d11c014b5602c28495c6f82b515542860e0

fix: handling of totalTimeout on sql plan refresh

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableClientContext.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableExporterUtils.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsConstants.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsView.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/Util.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/ErrorCountPerConnectionTest.java

Building on #2515, this creates a private instance of otel for internal metrics. This is necessary for a follow up pr that will introduce a new internal monitored resource
Changes:
- create a separate setting for disabling internal metrics (since internal metrics will not support customer provided exporters)
- create internal metrics as part of BigtableClientContext creation
- split off internal views
Change-Id: Iaafc327f3f008bcc29510594210e0914342f84fe

chore: create a separate otel instance for internal metrics

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableClientContext.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableExporterUtils.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/Util.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporterTest.java

This unifies the k8s_container & gce_instance monitored resources. In addition it adds some client specific attributes on the new monitored resource to make it easier to debug customer issues
Change-Id: Ic0a3b2efeb486a82dab53028ee524fe473a619ad

chore: migrate internal metrics to use bigtable_client monitored resource

---

google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableClientContext.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableExporterUtils.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsConstants.java

This will export a relevant subset of the metrics described in https://github.com/grpc/proposal/blob/master/A78-grpc-metrics-wrr-pf-xds.md as internal metrics to help rollout of DirectAccess
Change-Id: Ifddadb84d091f0f904f8f0f6e8da52de552e9757

chore: export internal DirectAccess gRPC metrics to the new bigtable_client monitored resource

---

google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableClientContext.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/CloudEnv.java

fix: use service name as the default audience

---

google-cloud-bigtable-deps-bom/pom.xml
google-cloud-bigtable-emulator-core/pom.xml

This should resolve the dry-run error:
```
{
"pkg:maven/com.google.cloud/google-cloud-bigtable-emulator-core@0.198.0": [
"Project name is missing"
],
"pkg:maven/com.google.cloud/google-cloud-bigtable-deps-bom@2.61.0": [
"Project name is missing"
]
}
```
b/427182301

ci: add name elements for the POM.xml files

---

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/Util.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableMaterializedViewIT.java

fix: populate table id for materialized view

---

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/sql/PlanRefreshingCallableTest.java

Change-Id: I806076a455be746f8d0ef3a63f70b53cf49f5820

test: deflake prepare plan refresh timeout test

---

google-cloud-bigtable/pom.xml
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminSettingsTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableCmekIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/ConsistencyRequestTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/GCRulesTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/internal/AbstractProtoStructReaderTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/internal/ProtoStructTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/internal/ResultSetImplTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/ExecuteQueryIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/StreamingMetricsMetadataIT.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/CookiesHolderTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/RetryInfoTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/changestream/ChangeStreamStateMachineTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/ErrorCountPerConnectionTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java
google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/sql/ExecuteQueryCallableTest.java
pom.xml

Change-Id: I273e614ab8d5e8e1bf73e031e80729dda0b2f0de

test: add errorprone and fix all of the errors

---

.github/release-please.yml
.github/sync-repo-settings.yaml

chore: create LTS branch 2.60.x

---

google-cloud-bigtable/clirr-ignored-differences.xml
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/grpc/BigtableChannelPool.java
google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/grpc/BigtableChannelPoolSettings.java

Experiments have shown that least-in-flight balancing is particularly effective when some channels or backends have problems.
Depends on: https://github.com/googleapis/java-bigtable/pull/2651

feat: Load balancing options for BigtableChannelPool

---

test-proxy/src/main/java/com/google/cloud/bigtable/testproxy/CbtTestProxy.java
test-proxy/src/main/java/com/google/cloud/bigtable/testproxy/ResultSetSerializer.java
test-proxy/src/main/proto/test_proxy.proto

Test proxy needs to build the proto type dynamically so it can properly construct the response message. 
Change-Id: Ie930064363d92d61daad498e8380dd87ab6722dd
This is needed for the test proxy to read values from proto/enum columns, as the current API `getProtoMessage(int columnIndex, AbstractMessage message)` and `getProtoEnum(int columnIndex, Function<Integer, ProtocolMessageEnum> forNumber)` mandates such a message object or static function as the second argument.
⚠️  **Reviewer Guidance: Unconventional Approach**
The solution implemented here for handling Enum is quite hacky (and implemented via Gemini), so it should be reviewed with extra attention.
~~The way we build the internal proto registry (`messageDescriptorMap`, `enumDescriptorMap`) from a `FileDescriptorSet` is also not …

textproxy: Allow testproxy to build its own proto registry
