google-cloud-bigtable-bom/pom.xml, pom.xml
=> feat: add bom

google-cloud-bigtable-bom/pom.xml, grpc-google-cloud-bigtable-admin-v2/pom.xml, grpc-google-cloud-bigtable-v2/pom.xml, pom.xml, proto-google-cloud-bigtable-admin-v2/pom.xml, proto-google-cloud-bigtable-v2/pom.xml, versions.txt
=> fix: align version numbers for proto and grpc versions

google-cloud-bigtable/pom.xml, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/DirectPathFallbackIT.java
=> chore: fix tests for targeting test env

google-cloud-bigtable/pom.xml
=> chore: allow prod test endpoint overrides separate from directpath

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
=> chore: use zones that are available in all test envs

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
=> chore: fix integration test zones to work across all environments

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/DefaultRowAdapter.java
=> chore: stop using bleeding edge guava features

README.md
=> docs: update README to include CI Status

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/DirectPathFallbackIT.java
Sometimes the test fails. I believe this is due to CloudPath connections
winning the race with DirectPath. To workaround this issue, this PR
waits until ipv6 traffic is observed via DirectPath before testing
fallback
=> chore: deflake DirectPathFallback test

google-cloud-bigtable-deps-bom/pom.xml, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java
=> deps: update core dependencies for google-cloud-core and gax

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/ResourceHeaderTest.java
This will unblock work on some experimental internal routing work
=> chore: promote app_profile_id to request headers

.repo-metadata.json
=> docs(fix): update client documentation link

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/HeadersTest.java
Reverts googleapis/java-bigtable#318
The header keys should match the request fields
=> Revert "fix: change app_profile_id to the correct header app_profile"

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
=> cleanup: update direct path endpoint

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/FakeServiceHelper.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/BigtableChannelPrimerTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/HeadersTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java
=> test: Refactor tests to extract common setup logic

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableBackupIT.java
Cluster ID was null which was causing the tests to skip. Additionally did some cleanup on test structure
=> test(fix): do not skip backup ITs

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableBackupIT.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/CloudEnv.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/EmulatorEnv.java
=> test(fix): use consistent endpoint for all table admin clients in test

README.md
we are using https://github.com/googleapis/java-shared-dependencies/blob/master/pom.xml#L73
=> chore: fix opencensus version in readme

.readme-partials.yml, README.md, synth.py
=> docs: use autogenerated readme functionality and regenerate

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java
=> fix: fix MetricTracerTest to rebase on head

.readme-partials.yml
=> chore: move gfe metrics readme

synth.py
Addresses changes like: https://github.com/googleapis/java-bigtable/pull/561#pullrequestreview-554204332
Raised https://github.com/googleapis/synthtool/issues/903 to address comment issue.
=> chore: add remove_method api for latest microgen changes

.readme-partials.yml
Move the changes in https://github.com/googleapis/java-bigtable/pull/613 to the correct file.
=> chore: move readme changes on stackdriver examples

samples/snippets/src/main/java/com/m/examples/bigtable/HelloWorld.java, samples/snippets/src/main/java/com/m/examples/bigtable/Quickstart.java
=> samples: remove _veneer from Bigtable region tags

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/RowMerger.java
=> chore: update row merger

.github/release-please.yml, .github/sync-repo-settings.yaml
=> build: configure branch 1.22.0-sp as a release branch

google-cloud-bigtable/pom.xml, pom.xml
=> fix: exclude protobuf from conformance-tests

pom.xml
=> fix: revert conformance test version

samples/snippets/src/main/java/com/example/bigtable/ConfigureConnectionPool.java, samples/snippets/src/test/java/com/example/bigtable/ConfigureConnectionPoolTest.java
=> docs: fix connection pool size for samples

.github/release-please.yml
https://github.com/googleapis/release-please/issues/968
=> chore: allow updating extra files in 1.22.0-sp branch

.github/workflows/ci.yaml
=> build: remove linkage monitor check

.github/workflows/ci.yaml
=> build: use maven 3.8.1 for ci

google-cloud-bigtable-stats/pom.xml
=> chore: fix pom version and skip publishing

google-cloud-bigtable-stats/pom.xml
=> chore: revert skip publishing for bigtable-stats module

google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/MavenPlaceholderShaded.java
=> fix: add placeholder class for bigtable-stats

pom.xml
=> fix: remove stats from javadoc

samples/native-image-sample/pom.xml
=> docs(sample): remove unused native-image-support dependency

google-cloud-bigtable-emulator/pom.xml
=> chore: fix version tag

samples/native-image-sample/README.md
=> docs(sample): update README for native image sample

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracerTest.java
=> fix: fix flaky test

google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/StatsWrapper.java, google-cloud-bigtable-stats/src/test/java/com/google/cloud/bigtable/stats/ITBuiltinViewConstantsTest.java, google-cloud-bigtable-stats/src/test/java/com/google/cloud/bigtable/stats/StatsRecorderWrapperTest.java
=> fix: enable integration test for google-cloud-bigtable-stats

README.md, google-cloud-bigtable-stats/pom.xml, google-cloud-bigtable-stats/src/main/resources/META-INF/license/apache2-LICENSE.txt, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
=> chore: add opencensus lincese and update readme

README.md, google-cloud-bigtable/pom.xml
=> fix: make cloud-monitoring a runtime dependency

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/BuiltinMetricsIT.java
=> test: disable integration test

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/BuiltinMetricsIT.java
=> fix: rename metric names to match the external name

README.md, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/internal/RowMergerUtil.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/DefaultRowAdapter.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/internal/RowMergerUtilTest.java
This is a feature for an internal google integration
=> chore: add internal api for row merging

.readme-partials.yml, README.md
=> chore: Fix the cloud bigtable link in readme

README.md, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracerTest.java
=> test: add a test for fix #1477 and few other tests to increase coverage

README.md, google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/BigtableStackdriverStatsExporter.java
=> fix: fix metric client settings

test-proxy/README.md
=> chore: update readme to build the root directory first

.kokoro/presubmit/graalvm-native-17.cfg, .kokoro/presubmit/graalvm-native.cfg
=> chore: update native image checks to use graalvm-22.3.0

samples/native-image-sample/pom.xml
=> fix: resolve merge conflict in samples/native-image-sample/pom.xml

.readme-partials.yml, README.md
=> chore: update readme on client side metrics

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java
=> fix: Call attemptStarted method with the request

README.md, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/CloudEnv.java
=> fix: make channel priming work with batch endpoint

google-cloud-bigtable/clirr-ignored-differences.xml, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Heartbeat.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamRecordTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/changestream/ChangeStreamRecordMergingCallableTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/changestream/ReadChangeStreamMergingAcceptanceTest.java
=> fix: Change the return type of Heartbeat::getEstimatedLowWatermark to long

README.md, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/changestream/ChangeStreamStateMachine.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/changestream/ChangeStreamStateMachineTest.java
=> fix: Fix StackOverflow in ChangeStreamStateMachine due to excessive mods

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/BuiltinMetricsIT.java
=> test: fix type in test

README.md, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
=> fix: mark readRow requests as unary operations

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableBatchingCallSettings.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataSettingsTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/BigtableBatchingCallSettingsTest.java
=> feat: add APIs to enable batch write flow control

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
=> feat: send feature flag when flow control is enabled

test-proxy/README.md, test-proxy/src/main/java/com/google/cloud/bigtable/testproxy/CbtTestProxy.java, test-proxy/src/main/proto/test_proxy.proto
=> test(fix): update the test proxy to sync with the recent test update

test-proxy/src/main/java/com/google/cloud/bigtable/testproxy/CbtTestProxy.java
Change-Id: I80254c0613e2bac8752d361434a3711c8f9a31b4
=> test: workaround existing bug in gax that prevents conformance tests from passing

samples/snippets/src/main/java/com/example/bigtable/Reads.java, samples/snippets/src/test/java/com/example/bigtable/ReadsTest.java
Change-Id: Id03b5105afe609cae61ae84e484b53b1860daf92
=> test: fix samples for reverse scans

README.md, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
=> fix: update default sample row key attempt timeout to 5 min

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/BulkMutation.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/RowMutationEntry.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsBatchResource.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsBatchingDescriptor.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/BulkMutateIT.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/BulkMutationTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsBatchingDescriptorTest.java
=> fix: fix batch mutation limit

.github/release-please.yml, .github/sync-repo-settings.yaml, README.md
enable releases
```
release-brancher create-pull-request \
--branch-name="2.23.x" \
--target-tag="v2.23.3" \
--repo="googleapis/java-bigtable" \
--pull-request-title="chore: setup 2.23.x lts branch" \
--release-type=java-backport
```
=> chore: setup 2.23.x lts branch

CONTRIBUTING.md
This adds instructions on how to run the code formatter to CONTRIBUTING.
=> chore: Add code formatting instructions to CONTRIBUTING

.github/workflows/ci.yaml, .github/workflows/conformance.yaml
=> ci: configure the protected branch

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminSettings.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminSettingsTest.java, grpc-google-cloud-bigtable-admin-v2/clirr-ignored-differences.xml
=> test: fix tests

google-cloud-bigtable-deps-bom/pom.xml
Change-Id: I14ac3a23adb0d137d72ac620884c00aee7095f70
=> chore: migrate to gapic-libraries-bom

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
Change-Id: Ia6d01f61361d48915708e168d5dbed26faa9e7e7
=> chore: migrate to improved batch throttling feature flag

README.md, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java
Change-Id: Ie10fb9e337306eb05994c68d6d094128800dcff7
=> test: don't hide stacktraces in BigtableInstanceAdminClientIT tests

.kokoro/presubmit/graalvm-native-17.cfg, .kokoro/presubmit/graalvm-native.cfg
=> chore: update graalvm container images to 22.3.3

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
=> feat: enable feature flag when setting is enabled

.kokoro/conformance.sh, test-proxy/src/main/java/com/google/cloud/bigtable/testproxy/CbtTestProxy.java
In the conformance test, create the client with retryInfo and routing cookie disabled. Run all the tests except for the tests that specifically test the features, which are expected to fail because client is not handling them.
Also create another client with both features enabled and expected the tests to succeed.
=> test: update conformance settings

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/RetryInfoTest.java
Add more retry info test to test the scenario where server stopped sending retry info and client handles retry correctly.
=> test: add RetryInfo test to test server disabled sending retry info

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/StateMachine.java
Change-Id: Ieebc425d359a426d24c1ed69d0093e97635bd742
=> chore: make sure to include the new row key in row merging errors

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
=> chore: refactor factory class

.github/workflows/unmanaged_dependency_check.yaml, renovate.json
In this PR:
- Change renovate configuration to update the version unmanaged dependency check along with `sdk-platform-java-config`.
=> chore: configure unmanaged dependency check version

README.md, pom.xml
=> chore: use sdk-platform-java-config in parent pom.xml

README.md, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/CloudEnv.java
=> chore: update CloudEnv.java

google-cloud-bigtable-stats/clirr-ignored-differences.xml
=> chore: fix clirr error.

google-cloud-bigtable-stats/clirr-ignored-differences.xml
=> chore: fix `to` parameter for clirr

.github/release-please.yml, .github/sync-repo-settings.yaml
=> chore: enable releases for 2.30.x branch

.cloudbuild/samples_build.yaml, README.md, samples/snippets/src/test/java/com/example/bigtable/QuickstartTest.java
=> ci: adding sample build

README.md, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/internal/NameUtil.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/AuthorizedView.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateAuthorizedViewRequest.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/FamilySubsets.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/SubsetView.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/UpdateAuthorizedViewRequest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTests.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/internal/NameUtilTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableAuthorizedViewIT.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/AuthorizedViewTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateAuthorizedViewRequestTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/FamilySubsetsTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/SubsetViewTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/UpdateAuthorizedViewRequestTest.java
Change-Id: Ie31eae6da61ed0d0462e029f6247924785b239bf
=> feat: Add admin APIs for AuthorizedView

README.md, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/SampleRowsIT.java
Change-Id: I37927d1b0a3502f6554e575ac44d4d92417d7d26
=> test: Rewrite SampleRowKeys IT on AuthorizedView

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/TestEnvRule.java
Change-Id: I9a4de8ecdaa3a1d096117853cc27805c7544fe04
=> test: fix clean up of tables with protected views

README.md, samples/snippets/src/main/java/com/example/bigtable/Filters.java, samples/snippets/src/main/java/com/example/bigtable/HelloWorld.java, samples/snippets/src/main/java/com/example/bigtable/KeySalting.java, samples/snippets/src/main/java/com/example/bigtable/Quickstart.java, samples/snippets/src/main/java/com/example/bigtable/Reads.java, samples/snippets/src/main/java/com/example/bigtable/WriteBatch.java, samples/snippets/src/main/java/com/example/bigtable/WriteConditionally.java, samples/snippets/src/main/java/com/example/bigtable/WriteIncrement.java, samples/snippets/src/main/java/com/example/bigtable/WriteSimple.java, samples/snippets/src/main/java/com/example/bigtable/deletes/BatchDeleteExample.java, samples/snippets/src/main/java/com/example/bigtable/deletes/ConditionalDeleteExample.java, samples/snippets/src/main/java/com/example/bigtable/deletes/DeleteFromColumnExample.java, samples/snippets/src/main/java/com/example/bigtable/deletes/DeleteFromColumnFamilyExample.java, samples/snippets/src/main/java/com/example/bigtable/deletes/DeleteFromRowExample.java, samples/snippets/src/test/java/com/example/bigtable/HelloWorldTest.java, samples/snippets/src/test/java/com/example/bigtable/MobileTimeSeriesBaseTest.java, samples/snippets/src/test/java/com/example/bigtable/QuickstartTest.java, samples/snippets/src/test/java/com/example/bigtable/deletes/DeletesTest.java
Change-Id: I155f73e142169989b2e74c906456d97107462227
=> samples: Update all examples to use TargetId-based data methods

README.md, samples/snippets/src/main/java/com/example/bigtable/AuthorizedViewExample.java, samples/snippets/src/main/java/com/example/bigtable/HelloWorld.java, samples/snippets/src/test/java/com/example/bigtable/AuthorizedViewExampleTest.java, samples/snippets/src/test/java/com/example/bigtable/BigtableBaseTest.java, samples/snippets/src/test/java/com/example/bigtable/MobileTimeSeriesBaseTest.java, samples/snippets/src/test/java/com/example/bigtable/TableAdminExampleTest.java
Change-Id: I77bb799eb448275928bcf0b562c0d4e06870c96d
=> samples: Add AuthorizedView examples

.readme-partials.yml, README.md, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/CustomOpenTelemetryMetricsProvider.java
=> chore: update readme on metrics

README.md, samples/install-without-bom/pom.xml, samples/snippets/pom.xml, samples/snippets/src/main/java/com/example/bigtable/InstanceAdminExample.java, samples/snippets/src/main/java/com/example/bigtable/TableAdminExample.java, samples/snippets/src/test/java/com/example/bigtable/InstanceAdminExampleTest.java, samples/snippets/src/test/java/com/example/bigtable/TableAdminExampleTest.java
=> samples: fix sample versions and clean up resource

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactory.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
=> fix: add more error handling

.readme-partials.yml, README.md
=> chore: update readme file

README.md, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/UnaryMetricsMetadataIT.java
=> test: fix flaky test

README.md, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
Also reduces logging when there are continuous failures (like permission denied).
=> chore: better error message when metric publish failed

README.md, google-cloud-bigtable-bom/pom.xml
Change-Id: I903aa34db7114bf410eaef179de6506cebc0e108
=> fix: remove stale module from bom

README.md, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/CloudEnv.java
This should unblock #2033 which disables directpath by default
=> test: ensure that directpath is enabled for direct path tests

.github/release-please.yml, .github/sync-repo-settings.yaml
=> chore: setup 2.39.x lts branch

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/ExecuteQueryIT.java
=> test: Add ExecuteQuery integration tests for SQL

.github/workflows/hermetic_library_generation.yaml, generation_config.yaml
#2334 accidentally changed googleapis commit and workflow file, revert these changes.
=> chore: restore library generation workflow

renovate.json
In this PR:
- Update renovate to manage action from sdk-platform-java
- Group dependency updates from sdk-platform-java in one PR.
=> chore: setup renovate to update action

test-proxy/src/main/java/com/google/cloud/bigtable/testproxy/CbtTestProxy.java, test-proxy/src/main/java/com/google/cloud/bigtable/testproxy/CbtTestProxyMain.java, test-proxy/src/main/proto/test_proxy.proto
This is used for internal testing frameworks to be able to run results through the test proxy
=> feat: Test proxy support SSL backend

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
Change-Id: I81d16773980bff6232ffe20839a9968718a361b1
=> chore: add feature flags for DirectAccess

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracer.java
Change-Id: Ide37e9226983ffaa32d8d2cda03c1fd8d1ad7fff
=> chore: remove unnecessary variable

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/TransformingServerStreamingCallable.java
Change-Id: I0fed7ea426a4b775a7fe5e661ed8e67f1faa53eb
=> chore: make server streaming transformer safer

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/SkipTrailersTest.java
Change-Id: I43324a0916e61e67ff3b7019189a9c54afae38ba
=> chore: deflake trailer skipping test

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/BuiltinMetricsIT.java
Change-Id: I8e7578fa4c5af6e8dcde04201ec7d6aa9c8f8762
=> chore: include metric name in error message

.github/workflows/hermetic_library_generation.yaml, .github/workflows/unmanaged_dependency_check.yaml, .kokoro/presubmit/graalvm-native-17.cfg, .kokoro/presubmit/graalvm-native.cfg, google-cloud-bigtable-bom/pom.xml, google-cloud-bigtable-deps-bom/pom.xml, pom.xml
renovate bot did not create a PR, so this PR was manually created by following the [last renovate bot PR for updating sdk platform java dependencies](https://github.com/googleapis/java-bigtable/pull/2384)
=> deps: update sdk-platform-java dependencies

samples/snippets/pom.xml
This is my manual renovate invocation.
=> chore(deps): update dependency com.google.cloud:libraries-bom to v26.50.0

google-cloud-bigtable-deps-bom/pom.xml
Change-Id: I13f78d94d3f1e775e24168c7f3c1cabd9a96d6d1
=> deps: revert downgrade grpc to 1.67.1 #2366

.kokoro/build.sh
- skip overlapping checks
- fail fast on test errors
=> test: improve testing workflow

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/BuiltinMetricsIT.java
Change-Id: I6d23530f0590faef67869da66da7fda0b0ffa73b
=> test: temporarily disable flaky test

README.md, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/TestEnvRule.java
Change-Id: Id15852b2b3bbb62746861d7ec02842353612ae77
=> test: fix clean up of protected & cdc tables

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/AppProfile.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClientTests.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/AppProfileTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateAppProfileRequestTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/UpdateAppProfileRequestTest.java
=> test: replace getDefaultInstance with newBuilder.build

.github/release-please.yml, .github/sync-repo-settings.yaml
=> feat: next release from main branch is 2.54.0

pom.xml
RenovateBot didn't create a pull request somehow.
=> deps: sdk-platform-java-config 3.45.1

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClient.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminSettings.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/internal/NameUtil.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateMaterializedViewRequest.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/MaterializedView.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/UpdateMaterializedViewRequest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClientTests.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminSettingsTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/internal/NameUtilTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateMaterializedViewRequestTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/MaterializedViewTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/UpdateMaterializedViewRequestTest.java
=> feat(bigtable): Add support for Materialized Views in Admin API

.github/scripts/update_generation_config.sh
Manual update while https://github.com/googleapis/sdk-platform-java/issues/3701 is not solved
=> chore: update update_generation_config.sh

.github/workflows/update_generation_config.yaml
A follow up PR of #2524 to sync workflow.
=> chore: sync workflow to update gen config

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/LargeRowIT.java
=> feat: large-row-skip | IT are running now

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
Change-Id: Ife688d7dc8e24ba5c4722bb3bc26401cae604d71
=> fix: remove debug messages

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/DirectPathFallbackIT.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/ExecuteQueryIT.java
Change-Id: Ie1d14cc80ef26b4f35f6005d5d213d4cf436d950
=> test: fix directpath tests

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableLogicalViewIT.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableMaterializedViewIT.java
=> test(bigtable): disable tests

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableClientContext.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsView.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/DefaultMetricsProvider.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/Util.java
=> fix: use universe domain when creating the monitoring client

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableClientContext.java
=> fix: close otel instance

CONTRIBUTING.md, google-cloud-bigtable-deps-bom/pom.xml, google-cloud-bigtable/clirr-ignored-differences.xml, google-cloud-bigtable/pom.xml, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracerStreamingCallable.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracerUnaryCallable.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracer.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracer.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerFactory.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/RpcMeasureConstants.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/RpcViewConstants.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/RpcViews.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/Util.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracerCallableTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/SimpleStatsComponent.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/StatsTestUtils.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/UtilTest.java
This reverts commit 7a46352124b8de9975abb51831a7ab4c7c88f598.
=> Revert "chore!: Remove opencensus (#2568)"

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableLogicalViewIT.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableMaterializedViewIT.java
=> test(bigtable): Enable tests

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/Table.java, google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/TableTest.java
=> chore: fix viewConfig in AutomatedBackupPolicy

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableMaterializedViewIT.java
=> tests(bigtable): fix mv tests zone

.github/release-please.yml, .github/sync-repo-settings.yaml
=> feat: next release from main branch is 2.62.0

google-cloud-bigtable/pom.xml, pom.xml
Change-Id: Iad08446a65b201f1ca14dfef4c8392c755f56fb4
=> chore: fix old build todo

google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/internal/ProtoResultSetMetadata.java, google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/SampleRowKeysRequest.java
Change-Id: I10bfd50174fe2c790aa4a10086a3b14017ba6156
=> chore: add missing hashCodes

google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/EmulatorEnv.java
Change-Id: I56119f9cce8abe8317fc9580a13f4588035de80d
=> test: disable metrics for emulator based ITs

.github/workflows/unmanaged_dependency_check.yaml, .kokoro/presubmit/graalvm-native-a.cfg, .kokoro/presubmit/graalvm-native-b.cfg, .kokoro/presubmit/graalvm-native-c.cfg, google-cloud-bigtable-bom/pom.xml, google-cloud-bigtable-deps-bom/pom.xml, pom.xml
Updating shared dependencies manually. Reference: https://github.com/googleapis/java-bigtable/pull/2616
=> deps: Update shared dependencies
